config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get '/sign_up' , to: 'users#new'
  get '/users/profile/:id' , to: 'users#profile'
  patch '/users/profile/:id' , to: 'users#profile_edit'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/posts/my_index' , to: 'posts#my_index'
  get '/posts/show/:id' , to: 'posts#show'
  get '/posts/show/:post_id' , to: 'posts#show'
  post '/posts/show/:post_id' , to: 'reservations#create'
  get '/my_reservations' , to: 'reservations#index'
  
  resources :users
  resources :posts  , shallow: true do
    resources :reservations
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <p>© 2020 POTEPAN.INC.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="header-inner">
    <div class="header-left-nav">
      
      <%= link_to root_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
      
      <%= form_with url: posts_path , method: :get, local: true do |f| %>
        <div class="header-sharch d-lg-inline-block d-none">
          <%= f.text_field :area ,class: "form-control" , placeholder: "エリア"  %>
          <i class="fas fa-map-marker-alt"></i>
        </div>
        <div class="header-sharch d-lg-inline-block d-none">
          <%= f.text_field :keyword ,class: "form-control" ,placeholder: "キーワード" %>
          <i class="fas fa-search"></i>
        </div>
        <%= f.submit 'Search', :name => nil ,class: "d-none" %>
      <% end %>
      
    </div>
    <div class="header-right-nav">
      <div class="nav-item">
        <% if logged_in? %>
          <li class="dropdown">
            
            
            <%= current_user.name %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="mx-3 p-1 host-icon nav-trigger">
                <%= render 'layouts/icon' %>
              </span>
              <b class="caret"></b>
            </a>
            
            <ul class="dropdown-menu">
              <li><%= link_to "ルーム登録", new_post_path %></li>
              <li><%= link_to "予約済みルーム一覧", '/my_reservations' %></li> 
              <li><%= link_to "登録済みルーム一覧", posts_my_index_path %></li>
              <li><%= link_to "設定", current_user %></li>
              <li class="divider"></li> 
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <%= link_to "ログイン","/login",{class: "btn btn-primary my-2 mx-3"} %>
          <%= link_to "登録する","/users/new",{class: "btn btn-secondary"} %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_icon.html.erb
<% if current_user.image? %>
  <img src='<%= current_user.image.to_s %>' class="host-icon" >
<% else %>
  <%= image_tag 'default_icon.jpg' ,class: "host-icon" %>
<% end %>

app/views/layouts/_my_posts.html.erb
<% @posts.each do |mine| %>
  <tbody>
    <tr>
      <td><%= link_to (image_tag  "#{mine.image_url(:thumb_my_posts)}" ,class: "room-posts-image"), "/posts/show/#{mine.id}"   %></td>
      <td class="posts-name"><%= link_to mine.name , "/posts/show/#{mine.id}"  %></a></td>
      <td class="posts-content"><%= mine.introduction %></td>
      <td class="price-icon"><%= mine.price %></td>
      <td><%= mine.created_at %></td>
    </tr>
  </tbody>
<% end %>

app/views/layouts/_user_nav.html.erb
<div class="col-lg-2 user-nav user-nav d-lg-none" >
  <ul>
    <li class= <%= "active" unless request.url.include?("profile") %> ><%= link_to "アカウント", current_user %></li>
    <li class= <%= "active" if request.url.include?("profile") %> ><%= link_to "プロフィール", "/users/profile/#{@user.id}"  %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoteShareAPP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
   
    <!-- <%= debug(params) if Rails.env.development? %>-->
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/yobi.html.erb
<div class="panel-area m-5">
            <h1 class="section-title">おすすめのエリア</h1>
            <div class="row">
                <div class="panel-item col-lg-3 col-6">
                    <span>東京</span>
                    <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E6%9D%B1%E4%BA%AC"><img class="panel-image" src="/assets/img_tokyo.jpg"></a>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>大阪</span>
                    <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E5%A4%A7%E9%98%AA"><img class="panel-image" src="/assets/img_osaka.jpg"></a>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>京都</span>
                    <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E4%BA%AC%E9%83%BD"><img class="panel-image shadow" src="/assets/img_kyoto.jpg"></a>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>札幌</span>
                    <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E6%9C%AD%E5%B9%8C"><img class="panel-image" src="/assets/img_sapporo.jpg"></a>
                    <div class="shadow"></div>
                </div>
            </div>
        </div>